spring.application.name=careerTrack

spring.datasource.url=jdbc:mysql://localhost:3306/careertrack
spring.datasource.username=Nidhi123
spring.datasource.password=Nidhi123

#turn off spring boot banner mode to off
spring.main.banner-mode=off

#specify the logging level 
logging.level.root=WARN

spring.jpa.hibernate.ddl-auto=update